### ISSUE TITLE
No search results from recent nightlies for major ZIM files?

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-tools#130]
This sounds almost too daft to be true, however in my recent discussions with @kelson42 and during related testing of kiwix-serve and kiwix-search I'm not getting any search results listed for major ZIM files. 

I've tried 2 operating systems (CentOS 6.9 64-bit on Intel and Raspbian Wheezy on ARM - a Raspberry Pi Model B 3).

At best I get `No results were found for klaus` from kiwix-serve when searching against the German Wikipedia. The other main ZIM file is Wikipedia for Uganda. 

When I run `kiwix-serve` with `--verbose` I can see the requests are being received and logged to the screen & http 200 response codes being returned. 

When I run the commands with no parameters I get the usage output so I know that the programs can write to the screen.

I've tried the nightlies for 2017-12-18 (for ARM) http://download.kiwix.org/nightly/2017-12-18/kiwix-tools_armhf_2017-12-18.tar.gz and 2017-12-17 for linux x64 http://download.kiwix.org/nightly/2017-12-17/kiwix_tools_linux64_2017-12-17.tar.gz

I do get some results for `wikipedia_fr_test_2017-11.zim` not always what I'd expect (I'll raise a separate issue for those observations).

@kelson42 has explained the project is transitioning to ZIM files that have embedded ZIM files and it's possible (but not easy) to learn whether a ZIM file is tagged as having full text. So perhaps it's a matter of the current tools not supporting other ZIM files? if so, is this by design or accident?

It'd be wonderful to be able to quickly, correctly and consistently know what to expect from the various tools; and if they're not intended to work with previous ZIM files that don't have an embedded FT index for the software to say so :) 

I'd like to be able to help test search. At the moment I seem to be running into various issues that make it hard to know what's going on and what's intended to work. All information and help appreciated so I can do so. Thank you.

**Comment by kelson42** [comment]
@julianharty There nothing much I can do with this ticket because the necessary information for a reprocase are missing. Please - in all tickets - answer the following points:
* What I do (step-by-step)
* What I get (detailed description)
* What you want (detail description)

**Comment by julianharty** [comment]
I get no results, just a 0 return code.

Anyway, to help you reproduce the effects:
Download the nightly builds from the links I provided when raising this issue. Extract the files. You can either run them on the same OS or I expect you'll get similar results on a recent version of Ubuntu.

For completeness here are example command lines. They are copy+pasted here as is, as I ran them in sequence. Notice there are no results returned. I'd expect at least one result
```
$ ./zimsearch wikipedia_en_uganda_09_2014.zim Kampala
$ ./kiwix-search wikipedia_en_uganda_09_2014.zim Kampala
$ ./zimsearch wikipedia_en_uganda_09_2014.zim a
$ ./kiwix-search wikipedia_en_uganda_09_2014.zim a
```
Regardless of what I search for I get no results for this ZIM file.  Similarly for wikipedia_de_all_novid_2017-08.zim  I get no results. Whereas the tiny test zim file `wikipedia_fr_test_2017-11.zim` does get search results
```
$ ./kiwix-search wikipedia_fr_test_2017-11.zim Warrington
Warrington
Summary
$ ./zimsearch wikipedia_fr_test_2017-11.zim Warrington
article 37
score 100	:	Warrington
article 38
score 59	:	Summary
```
 
Links to the ZIM files I used
http://download.kiwix.org/zim/wikipedia/wikipedia_de_all_novid_2017-08.zim
http://download.kiwix.org/zim/wikipedia/wikipedia_en_uganda_09_2014.zim
http://download.kiwix.org/zim/wikipedia/wikipedia_fr_test_2017-11.zim

What do I want? - at least one result, presumably several from any of the ZIM files.

If you do get results when you run the commands against the Ugandan and the German  files please can you paste the command lines you used and the results the programs output. I'll then try them here. I'm happy to also configure additional logging/debugging if you can explain how to do so.

**Comment by mgautierfr** [comment]
> At best I get No results were found for klaus from kiwix-serve when searching against the German Wikipedia. The other main ZIM file is Wikipedia for Uganda.

From what I see in `library_zim.xml`, it seems that neither German nor Uganda has full text index embedded. (There is no `_ftindex` tag in the tags).
So if you don't have a separated index (found in "portable" archives) alongside the zimfile, what you describe is normal. If you have a separated index (and locate it correctly for kiwix-serve (in library.xml or command line arguments)), this is a bug.

But I understand your need to have a full description of what is supported :)

# In a short sentence :

All old zim should be supported. Maybe not with last functionality but no deprecation has been planned.
There can be bugs and recent libzim/kiwix-* may crash or fail to read old zim. But they are bugs and should be fixed.

# With a bit longer explanation :

What kiwix-* may have to read can be :
- An "old" zim file without fulltext index (separated or integrated)
- An "old" zim file with fulltext index separated (in a different directory) 
- A new zim file with a fulltext index embedded. There is different "versions" of the fulltext index as I slowly add functionalities while @kelson42 were creating zim file with fulltext index. There is two may version we need to consider :
  - version "notitle" (mainly the same thing that for separated index, but embedded)
  - version "title" (Article's titles are also indexed in a separated xapian "namespace" 

Sadly, there is no (easy) way  to know which fulltext version is used in a zim. But we always use the lastest version when we are creating embedded fulltext zim.

On top of that, there is two kinds of search :
 - "Classical" search using full text index.
 - Suggestion that search only in title.

## Suggestion
Suggestion is always available and will do a "search" this way :
 - If there is a embedded fulltext :
   Mark the search as partial in Xapian( ie. append a `*` at the end of the search query)
     - with an fulltext version title => search in the specific xapian namespace.
     - with an version notitle => search in the fulltext index (the article content)
- If no embedded fulltext (or no result from previous search), we fallback to the previous behavior :
We search for titles (directly in the zim) starting with the search query (trying to be case insensitive)

Suggestion never use the external fulltext index.
In kiwix-serve, the suggestion result is what is displayed as suggestion in the search bar (topbar) when you start to enter text and before you validate your query.
If a fulltext is available, kiwix-serve will also append a extra entry in the suggestion to launch a fulltext (classical) search. (This is the entry at the end of the popup select with `...` at the end) 

## Search

Classical search is available only if a full text index is present (either embedded or separated).
If the fulltext index is embedded but the zim file is cut, we consider that no fulltext index is available.
Search is always made in the "content" namespace of xapian (never in the indexed titles).
The query stemmed, stop word are removed, and we do NOT add the `*` at the end.

In `kiwix-serve`, we also check if an article has the exact same title than the query before doing the search.
If this is the case, we directly redirect to this article.

## About [stemming](https://en.wikipedia.org/wiki/Stemming):

The idea of stemming is to reduce different variants of a word to the common root version.
(compute, computer, computation, computed => comput)
We are stemming words at indexation step (zim creation) and before doing a search (or suggestion). Stemming rules are language dependent, so searching an English sentence in a German index may return wrong result (even if the article itself is in English).
Stemming is made by Xapian, we don't have the hand on it (except specifying the language used)
However, we tell to Xapian to store in the database only the stemmed version of the words to reduce database space. I've the feeling that this could break a bit the search results of xapian, but we have to investigate more on this to be sure.

**Comment by kelson42** [comment]
So, I think we can close that one?

**Comment by julianharty** [comment]
@kelson42 Before we close this one I'd appreciate some examples that demonstrate the tools returning results for the 2 older files. I've tried searching for `Beinasco`  

This is the title of an article I know is in this file (and I can see the article in the Android app). But when I try this query using the nightly I mentioned earlier (running on CentOS 6.9 I still don't get any output.
```
$ ./kiwix-search wikipedia_de_all_novid_2017-08.zim Beinasco
$ 
```

**Comment by kelson42** [comment]
@julianharty As there is no FT search index in that ZIM file, there is not ft search. So your command works as intent.
@mgautierfr There is a problem here, the same command with `-s` still give not result. and it should give Beinasco as result.

**Comment by kelson42** [comment]
I have open a dedicated bug for the lastly discovered problem as this is quite far away from the initial bug report.

**Comment by julianharty** [comment]
Before closing this for good, perhaps you could demonstrate _by example_ where `kiwix-search` (for `zimsearch` would also be useful) actually does return something for older ZIM files, including the ones I've mentioned here. It's not enough to tell me the program's working as intended by returning no output - surely it's actually intended to return output for queries that *do* match content - you've yet to demonstrate this capability. 

Also, as a suggestion, if these tools are not intended to return _any_ output when used with older ZIM files, at least be kind to the users and tell them so when the program is run. The guessing game is a little tiring and unproductive. Think first of the user, and design the program(s) accordingly - what would they like to know about using the kiwix utilities? when would they like to know it? would working examples of expected behaviours help? Then we can test those expectations to make sure the programs are working as described/specified and intended :)

**Comment by mgautierfr** [comment]
Technically, `kiwix-search` is not intended to return any result for older zim files as they do NOT contain any full text index.

Before we embedded index in zim files, kiwix-search was intended to work on the separated xapian database (the `.idx` directory). Try to open a zim file with kiwix-search would simply fail.
If you want `kiwix-search` to return results for old zim files, you will have to use `kiwix-search` with the `.idx` directory, to the zim file.

When I've adde28e4da2352b3d7ee29ca1c0398e8601ad8bac313d embedded fulltext index in zim files, I quickly extend `kiwix-search` to allow it to open a zim file and search it the embedded fulltext index. But I've keep the previous behavior of searching only in the fulltext index.

The PR #136 changes this and make `kiwix-search` also look in the list of zim article to search for suggestion (and so behave like suggestion in `kiwix-serve`)

`zimSearch` is a old tool search in the internal fulltext database specific to the zim format. As far as know, this database was never used and when I integrate the xapian search in the libzim, I remove all the code for the specific zim fulltext format.
Doing so, I've update the `zimSearch` tool to use the xapian database instead of the zim specific one.
So, `zimSearch` is a tool that can search only in the embedded xapian fulltext index.
`kiwix-search` is a tool that can search in the embedded xapian fulltext index but only in a separated xapian database and (if #136 is merged) search suggestion in the zim list of article (no xapian).

**Comment by kelson42** [comment]
I'm not going to talk about `zimsearch` because this is not the correct place, because we treat one problem at a time and because `zimsearch` is a 10 years old unmaintained tool which somehow reappeared at the surface at the occasion of zim-tools launch. Please open a ticket in `zim-tools` git repo if you have concerns about it.

"surely it's actually intended to return output for queries that do match content"... Believe it or not but, the software can not magically returns a result if there is no ft index. Like written earlier "As there is no FT search index in that ZIM file, there is not ft search.". There is no ZIM ft search capability in that case.

What we did in the past is providing an external ft index as a separate directory. kiwix-search is not thought to deal with that external index... and I'm not sure this makes sense to implement that as this way of doing is already outdated. Anyway I have open a ticket for it and if this is easy (might be), maybe we will do it.
https://github.com/kiwix/kiwix-tools/issues/137

And yes I agree that it would be helpful that kiwix-search prints an error message if there is no ft index. Here is the ticket.
https://github.com/kiwix/kiwix-tools/issues/138
Hopefully we are through now with this thread.

**Comment by julianharty** [comment]
Thanks for planning the various enhancements and for explaining the purpose of the tools. It certainly wasn't obvious when we started this topic (and you didn't mention the limitations when we chatted on Sunday). With the various improvements, particularly #138 I agree this thread has served its purpose.

**Comment by mgautierfr** [comment]
> What we did in the past is providing an external ft index as a separate directory. kiwix-search is not thought to deal with that external index... and I'm not sure this makes sense to implement that as this way of doing is already outdated. Anyway I have open a ticket for it and if this is easy (might be), maybe we will do it.
#137 

You CAN already use `kiwix-search` with a external `.idx` directory. Simply pass the directory instead of the zim file in the arguments. This is the original behavior of `kiwix-search` and it have not been removed.

**Comment by kelson42** [comment]
@mgautierfr good, I have improved the usage() to document that and closed #137.
